### ISSUE TITLE
Change primary colors from config

### ISSUE THREAD

**Issue by fran-ny** [huyb1991/hugo-lamp#13]
Hi! Awesome, amazing theme! I've been searching for a easy, but good-looking, AMP theme.

I'm actually having trouble figuring out how to change the color scheme.  I tried a find in replace in the variable.scss file and in the stylesheet.html. I was unable to affect the color - could you help me figure out how to do this?

One cool feature would be to be able to change the variables (ie; primary) from the config.

Thanks for the cool theme

**Comment by huyb1991** [comment]
Hi @fran-ny ,
Thanks for your feedback, I will refactor variables soon. For now, to change colors in `variables.scss`, you should run watching scss script, go to `hugo-lamp` directory then run this command:

```bash
npm run watch
```

Then update colors in `variables.scss`, it will auto general new styles in `stylesheet.html`, Hugo will do other things (for auto build and reload).
Hope this help.

**Comment by huyb1991** [comment]
@fran-ny Please take a look on this PR for [#14 refactoring sass](https://github.com/huyb1991/hugo-lamp/pull/14).
The main of this PR is reduce sass variables for simpler, now you can update color in `variables.scss` file, please run command for watching sass changes as comment above.

Please check and give me your feedbacks, many thanks!

**Comment by fran-ny** [comment]
Hey @huyb1991 

My apologies for the late reply - just seeing your note. I am an R developer and working with your template as my blog through Rstudio blogdown. I will check out your suggestion, but I won't be working on my site again until next weekend.

Many thanks to you for the great template. It really is special

Best,
frn
