### ISSUE TITLE
Questions about configuration

### ISSUE THREAD

**Issue by andreabisello** [huyb1991/hugo-lamp#16]
Hi,
thanks for this awesome theme.
I have some questions, but i don't known it these are theme related or hugo related.
I try to ask : 

in config.toml i read
```

[taxonomies]
  tag = "tags"
  category = "categories"

```
what the meaning of this configuration?

then, i read

```
[[menu.main]]
  name = "Hugo"
  weight = 1
  identifier = "hugo"
  url = "/hugo/"
[[menu.main]]
  name = "AMP Project"
  weight = 2
  identifier = "amp"
  url = "/amp/"
[[menu.main]]
  name = "Tags"
  weight = 3
  identifier = "tags"
  url = "/tags/"
```

but the directory tree in the content directory is

/amp
/hugo
/post

and not

/amp
/hugo
/tags

so i understand 

* every contents in post will not be present in the menu amp or the menu tags
* every contents in /amp will be present in /amp menu
* every contents in /hugo will be present in /hugo menu
* /tags is a reserved keyword

thanks

**Comment by huyb1991** [comment]
Hi there,

1. Please take a look on [taxonomies documents](https://gohugo.io/content-management/taxonomies/), basiclly, this help to group content by the kind (tag, category). Here's an [example post content](https://raw.githubusercontent.com/huyb1991/hugo-lamp/master/exampleSite/content/amp/getting-started.md)
```yaml
title: "Getting Started with AMP"
date: 2018-05-31T07:11:59+07:00
draft: false
type: "post"
tags: ["AMP", "theme"]
```
This will set 2 tags `AMP` and `theme` for this post, you can set category for it too.

2. Please take a look on [Menus document](https://gohugo.io/content-management/menus/), the menu config here to add link to the menu (at sidebar of this theme), if we don't create menu here, we still can access to list urls:
```
domain/amp
domain/tags
domain/hugo
```
The menus is simple display links in our config via:
```
[[menu.main]]
  name = "Tags"
  weight = 3
  identifier = "tags"
  url = "/tags/"
```
The subfolers in `content/` are the content when we're creating new post by Hugo command `hugo new [postname]`, like: `hugo new amp/next-post.md`.

For your comment:
```
1. every contents in post will not be present in the menu amp or the menu tags
2. every contents in /amp will be present in /amp menu
3. every contents in /hugo will be present in /hugo menu
4. /tags is a reserved keyword
```
1. Content in post will display under `domain/post/`, and can display under `domain/tags/[tagname]` if this `tagname` added in tag in content config (as I explained above).
2 & 3. Correct
4. `/tags` will list all tags in website, this is taxonomy

Hope this help.
