### ISSUE TITLE
How to run exampleSite

### ISSUE THREAD

**Issue by pmeems** [huyb1991/hugo-lamp#20]
Perhaps a really stupid question, but I'm new to HUGO. I created a new site and cloned your theme.

I see I have a package.json in `\themes\hugo-lamp` and in `\themes\hugo-lamp\exampleSite`
How to run exampleSite? Should I move the content of the folder to my root? Overwriting my (still empty) content folder? And run `npm start` from my root?

**Comment by huyb1991** [comment]
Hi @pmeems ,
Yes, the `package.json`, `config.toml`, `content/` are the config and content for example, you should copy it in to your root folder, then update as your config (like name, description...). You can read details on Hugo document.

**Comment by pmeems** [comment]
Thanks for the response. I've got it working now.
I already have 1 AMP page: https://josephiena.nl/
I will try to merge my page with your layout and start creating the other pages.
