### ISSUE TITLE
Security Vulnerability - Github Warning

### ISSUE THREAD

**Issue by fran-ny** [huyb1991/hugo-lamp#22]
Hi, I got this note when I pushed to github:

"We found a potential security vulnerability in one of your dependencies.
A dependency defined in …/hugo-lamp/package-lock.json has known security vulnerabilities and should be updated.

Only the owner of this repository can see this message."

I deleted that package and everything seemed fine. Are you able to fix?

**Comment by huyb1991** [comment]
You can update it or ignore, because we build static file, file upload to server are static file, almost are HTML and CSS, some JS if you put it in, I think this is not big deal.
