### ISSUE TITLE
Robots.txt Enabling

### ISSUE THREAD

**Issue by fran-ny** [huyb1991/hugo-lamp#23]
Following the hugo instructions: https://gohugo.io/templates/robots/ I've added enableRobots.txt = true under [Params] in the config file. The robots.txt file was added to the layouts folder, but it is domain.com/robots.txt is currently 404ing. I don't know enough about the set up to know if this is a template-related issue or not. Do you know?

**Comment by huyb1991** [comment]
For robot file you can enable, then check in `public/` after run command `hugo`.
Or you can add it into the `<head>` tag on the tempalte file, here: https://github.com/huyb1991/hugo-lamp/blob/master/layouts/_default/baseof.html

Hope this help!

**Comment by fran-ny** [comment]
Thank you!

**Comment by aspose-com-kb** [comment]
Is this parameter even correct? enableRobots.txt
Shouldn't this be enableRobotsTXT?
This is not working for me at all. 

No robots.txt is being generated in the output folder, Any help? :(
