### ISSUE TITLE
please can you help me with relative path (fonts and images not found)

### ISSUE THREAD

**Issue by andreabisello** [huyb1991/hugo-lamp#25]
if i push the website in a root folder like example

http://www.recensionifacili.it/

with this in toml

baseURL = "http://www.recensionifacili.it/"

it works.

if i move here

https://www.machenotizia.info/articoli/

with this toml

baseURL = "https://www.machenotizia.info/articoli/"

some file are not found.

i tried also with

baseURL = "https://www.machenotizia.info/articoli"

nothing changed

![image](https://user-images.githubusercontent.com/2149815/44574464-c73fb780-a789-11e8-9992-668e7209d5bb.png)

it look like it searching from the root of the website, without considering /articoli/ path.

can you help me?

thanks.

**Comment by biomassives** [comment]
typically, in hugo, static resources like images, fonts, js files, are stored in the static folder located within the theme you are using.   for example: for /hugo-lamp/exampleSite/content
 ls themes/hugo-lamp/static/   shows..   fonts img directories..  hope this helps.. :)

**Comment by huyb1991** [comment]
Thanks @abioneperhobby for raising this issue, also thanks @biomassives explaining.

AMP page required push styles into `<style amp-custom>` at head, basically, I used `node-sass` to compile sass then inject to template at `./layouts/partials/stylesheet.html` , details at [build-script](https://github.com/huyb1991/hugo-lamp/blob/master/index.js).

I think we need a variable for static url at sass file, will take a look this issue on next week.

**Comment by huyb1991** [comment]
@abioneperhobby Please try this way:
For image, you need to update image src url with subfolder name.
For font, in SaSS file, you need to add variable for subfolder name, then use it in font-face url.
