### ISSUE TITLE
changing color [$green: #6aac0e] to $: #21abcd in variables.scss but does change color in theme 

### ISSUE THREAD

**Issue by alvarogutyerrez** [huyb1991/hugo-lamp#26]
Hello **huyb1991**, thank you so much for your contribution, I liked a lot the theme _Hugo Lamp_ and I started to use it regularly. But I have a small issue with the appearance, I want to change the baseline color of the theme from #6aac0e to #21abcd, but when I change this in the variables.scss file nothing changes when I do... 

> blogdown:::serve_site() 

can you please help me out with these issues?

Thank you again, 
Best regards, 

Álvaro.

**Comment by alvarogutyerrez** [comment]
Hello, sorry for the duplicate I just saw the [issue 13](https://github.com/huyb1991/hugo-lamp/issues/13), but the user does not report if your solition worked or not. I tryied

`npm run watch
`

But several errores showed up and this file was created on the main folder of my workdirectory

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
> 2 info using npm@3.5.2
> 3 info using node@v4.2.6
> 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> 5 info lifecycle hugo-lamp@1.0.2~prebuild: hugo-lamp@1.0.2
> 6 silly lifecycle hugo-lamp@1.0.2~prebuild: no script for prebuild, continuing
> 7 info lifecycle hugo-lamp@1.0.2~build: hugo-lamp@1.0.2
> 8 verbose lifecycle hugo-lamp@1.0.2~build: unsafe-perm in lifecycle true
> 9 verbose lifecycle hugo-lamp@1.0.2~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/alvaro/Dropbox/ReposGitHub/blogdown/TEMAS_VARIOS/HUGO-LAMP/node_modules/.bin:/home/alvaro/bin:/home/alvaro/.local/bin:/usr/local/stata15:/home/alvaro/anaconda2/bin:/home/alvaro/bin:/home/alvaro/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 10 verbose lifecycle hugo-lamp@1.0.2~build: CWD: /home/alvaro/Dropbox/ReposGitHub/blogdown/TEMAS_VARIOS/HUGO-LAMP
> 11 silly lifecycle hugo-lamp@1.0.2~build: Args: [ '-c', 'hugo && npm run optimize:html' ]
> 12 silly lifecycle hugo-lamp@1.0.2~build: Returned: code: 1  signal: null
> 13 info lifecycle hugo-lamp@1.0.2~build: Failed to exec build script
> 14 verbose stack Error: hugo-lamp@1.0.2 build: `hugo && npm run optimize:html`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at EventEmitter.emit (events.js:172:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at ChildProcess.emit (events.js:172:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:821:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 15 verbose pkgid hugo-lamp@1.0.2
> 16 verbose cwd /home/alvaro/Dropbox/ReposGitHub/blogdown/TEMAS_VARIOS/HUGO-LAMP
> 17 error Linux 4.15.0-42-generic
> 18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
> 19 error node v4.2.6
> 20 error npm  v3.5.2
> 21 error code ELIFECYCLE
> 22 error hugo-lamp@1.0.2 build: `hugo && npm run optimize:html`
> 22 error Exit status 1
> 23 error Failed at the hugo-lamp@1.0.2 build script 'hugo && npm run optimize:html'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the hugo-lamp package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     hugo && npm run optimize:html
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs hugo-lamp
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls hugo-lamp
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by huyb1991** [comment]
@alvarogutyerrez Did you run `npm install` command? To make sure all package are install. Then you can run `npm run watch`.
I just clone and run it, it works without error.

**Comment by alvarogutyerrez** [comment]
thanks so much for you quick answer. In fact I have npm installed. Although I re-run `npm install` in my Zorin (Ubuntu 14.06). I got this messages 

> $ **npm install**
> hugo-lamp@1.0.2 /home/alvaro/Dropbox/ReposGitHub/blogdown/TEMAS_VARIOS/HUGO-LAMP
> └── npm-watch@0.5.0 extraneous
> 
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
> npm WARN hugo-lamp@1.0.2 No repository field.
> 

And afterwards, when I try with `npm run watch`

$ **npm run watch**

> npm ERR! Linux 4.15.0-42-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch"
> npm ERR! node v4.2.6
> npm ERR! npm v3.5.2
> npm ERR! missing script: watch
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR! <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! /home/alvaro/Dropbox/ReposGitHub/blogdown/TEMAS_VARIOS/HUGO-LAMP/npm-debug.log


And Finally the debug file is this:

> 
> 
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'watch' ]
> 2 info using npm@3.5.2
> 3 info using node@v4.2.6
> 4 verbose stack Error: missing script: watch
> 4 verbose stack     at run (/usr/share/npm/lib/run-script.js:147:19)
> 4 verbose stack     at /usr/share/npm/lib/run-script.js:57:5
> 4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:345:5
> 4 verbose stack     at checkBinReferences_ (/usr/share/npm/node_modules/read-package-json/read-json.js:309:45)
> 4 verbose stack     at final (/usr/share/npm/node_modules/read-package-json/read-json.js:343:3)
> 4 verbose stack     at then (/usr/share/npm/node_modules/read-package-json/read-json.js:113:5)
> 4 verbose stack     at ReadFileContext.<anonymous> (/usr/share/npm/node_modules/read-package-json/read-json.js:284:20)
> 4 verbose stack     at ReadFileContext.callback (/usr/share/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
> 4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
> 5 verbose cwd /home/alvaro/Dropbox/ReposGitHub/blogdown/TEMAS_VARIOS/HUGO-LAMP
> 6 error Linux 4.15.0-42-generic
> 7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch"
> 8 error node v4.2.6
> 9 error npm  v3.5.2
> 10 error missing script: watch
> 11 error If you need help, you may report this error at:
> 11 error     <https://github.com/npm/npm/issues>
> 12 verbose exit [ 1, true ]



Thanks again for your help. I will try to reinstall _npm_ anyways during the night, and then I will let you know if it works, but maybe this logfile contains something that I am missing now.


Thanks you a lot,


Álvaro

**Comment by huyb1991** [comment]
@alvarogutyerrez Follow your error logs, I think you should upgrade node and npm version to latest.
```
npm ERR! node v4.2.6
npm ERR! npm v3.5.2
```

**Comment by huyb1991** [comment]
@alvarogutyerrez Is there any update? Did you run scripts in `themes/hugo-lamp` directory?

**Comment by huyb1991** [comment]
@alvarogutyerrez Use `yarn` instead of `npm install`. I will update it on README soon.
