### ISSUE TITLE
Stylesheet not serving

### ISSUE THREAD

**Issue by BolajiAyodeji** [huyb1991/hugo-lamp#27]
I tried to modify the variable.scss and other sass but it didn't render.
I ran the command `npm run watch` as expected but got error;

$ npm run watch

> hugo-lamp@1.0.2 watch C:\Hugo\Sites\thewebdev.io\themes\hugo-lamp
> nodemon -e scss -w ./ -x npm run build

'nodemon' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hugo-lamp@1.0.2 watch: `nodemon -e scss -w ./ -x npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hugo-lamp@1.0.2 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-01-18T16_26_38_190Z-debug.log

what could be wrong please?
PS: I've tried `npm install too`

**Comment by huyb1991** [comment]
@BolajiAyodeji  Did you run scripts in `themes/hugo-lamp` directory?
Please take a look on issue #13

**Comment by BolajiAyodeji** [comment]
I did it got this error!
```
npm run watch

> hugo-lamp@1.0.2 watch C:\Hugo\Sites\thewebdev\themes\hugo-lamp
> nodemon -e scss -w ./ -x npm run build

'nodemon' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hugo-lamp@1.0.2 watch: `nodemon -e scss -w ./ -x npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hugo-lamp@1.0.2 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-01-29T13_14_05_398Z-debug.log
```

**Comment by huyb1991** [comment]
I think the problem because the path of `./node_modules/.bin/nodemon` in watch script, maybe it wrong on Windows.
So, please try to install `nodemon` at global:
```
npm -i -g nodemon
```
Then update watch script in `package.json` to call nodemon global instead of local:
```
"watch": "nodemon -e scss -w ./ -x npm run build"
```

**Comment by Brantlab** [comment]
I think I am missing something. Can you point me in the right direction? 

```
S C:\Hugo\Sites\suchsuch.com\themes\hugo-lamp> npm -i -g nodemon

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    completion, config, create, ddp, dedupe, deprecate,
    dist-tag, docs, doctor, edit, explore, get, help,
    help-search, hook, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, profile, prune, publish, rb, rebuild, repo, restart,
    root, run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    C:\Users\SimplyTech\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.4.1 C:\Program Files\nodejs\node_modules\npm

PS C:\Hugo\Sites\suchsuch.com\themes\hugo-lamp>
```
