### ISSUE TITLE
rss icon not showing up

### ISSUE THREAD

**Issue by pablo-baeza** [huyb1991/hugo-lamp#34]
Hi,

The rss icon is not showing up in the sidebar (but the rss link is there and you can click on it), and all the social network icons disappear from the sidebar when you are inside a post (although, once again, the links are there and you can click on them, it's just that they're invisible). This happens in the example site as well when I access it using Firefox (inside Ubuntu) or using the browser from my android phone.

Do you know how to fix this? I'm playing around with the files in the meanwhile, but I thought it wouldn't hurt to ask.

PS. The "share on facebook" etc icons also become invisible when you're inside a post (but not on the home page)

**Comment by huyb1991** [comment]
Hi @pablo-baeza ,

I think this is old version using relative path of icon fonts, for last update, all icons is change to `svg` format, it should be worked. Could you help me check on your theme which kind of icons? `svg` or icon font.

**Comment by pablo-baeza** [comment]
Hi, thanks for the reply. I downloaded the theme yesterday so I think I have the most up-to-date version. From looking at the files I'm using svg format icons. This is what I see with the demo site that comes with the theme (notice the bottom of the sidebar where the rss icon is invisible, and the bottom of the post where the share on acebook etc icons are invisible):

![image](https://user-images.githubusercontent.com/7280608/54899099-088a7800-4ecf-11e9-8b1a-ae8946baf3b7.png)

And this is inside a post:

![image](https://user-images.githubusercontent.com/7280608/54899177-47203280-4ecf-11e9-945b-49a7b68c825f.png)
![image](https://user-images.githubusercontent.com/7280608/54899199-569f7b80-4ecf-11e9-9781-d0fc0fc1c875.png)

**Comment by huyb1991** [comment]
Hi @pablo-baeza ,

Fixed on https://github.com/huyb1991/hugo-lamp/commit/e64c652b7fb60010ead1b5ba6d3e2fdb9afcd64a and https://github.com/huyb1991/hugo-lamp/commit/7252e8205e86c973dd762944c3a4c9f5cb1e2162

Please get latest version on `master` branch.

Thanks you for issue reporting!

**Comment by pablo-baeza** [comment]
awesome, it works wonderfully now! Many thanks :)
