### ISSUE TITLE
Social media enhancements

### ISSUE THREAD

**Issue by JosephDomenici** [huyb1991/hugo-lamp#40]
It would be nice to have an SVG icon for Reddit in the bottom social media container. I tried my hand at generating an SVG path, but I wasn't able to get anything looking as good as your icons.

Also, it would be helpful to add Reddit to the list of social media share buttons on posts, and to make the list of which buttons appear configurable (as opposed to editing them in post/summary.html).

**Comment by huyb1991** [comment]
Hi @JosephDomenici ,
I added Reddit icon, please get latest code on `master` branch.

Don't forget to add reddit username in `config.toml` file, hope this help, thanks!

**Comment by JosephDomenici** [comment]
Works great. Thanks!
