### ISSUE TITLE
Side bar menu icon cannot be loaded.

### ISSUE THREAD

**Issue by lcron** [huyb1991/hugo-lamp#43]
Side bar menu icon cannot be loaded.
![image](https://raw.githubusercontent.com/lcron/static/master/images/Screenshot_2019-06-16-22-00-04-526_com.android.chrome.png)
This should be similar to #34, but it can click normally.

### Suggest

Sharing links in the summary are collect to a button.
Click on the button to select the sharing link.
Because users may join other sharing platforms, showing them all will have a negative impact, especially on small screen devices.

**Comment by huyb1991** [comment]
@lcron Could you please re-upload image, I can't see the image.

For social sharing buttons, that's for this theme, you can modify it if you want. I saw it common UI on other blog

**Comment by lcron** [comment]
> @lcron Could you please re-upload image, I can't see the image.
> 
> For social sharing buttons, that's for this theme, you can modify it if you want. I saw it common UI on other blog

I have updated the image link.
In fact, you can see the effect by browsing on your mobile phone.

**Comment by huyb1991** [comment]
@lcron Google+ icon is removed from this PR: https://github.com/huyb1991/hugo-lamp/pull/46
Google+ is no longer work, now just 2 icons for Facebook and Twitter, the issue is fixed, please help me check and confirm this one.
