### ISSUE TITLE
Add syntax highlighting

### ISSUE THREAD

**Issue by papayarules** [huyb1991/hugo-lamp#68]
Is there a way to add syntax highlighting to this theme? I followed the instructions from [this post ](https://tomspencer.dev/blog/2018/08/03/deploying-a-hugo-powered-site-to-netlify-with-source-code-syntax-highlighting/) and added
```
pygmentsUseClasses = true             # Enable for syntax highlighting
pygmentsCodeFences = true             # Enable triple backtick 'code fence' markdown
pygmentsStyle = "dracula"
```
to the toml and this in my post (back tricks without parenthesis)
``` 
(```) r
library(tidyverse)
mtcars >%> filter(mpg == 200) 
```
but I still don't see any highlighting in the rendered html. I'm using RStudio and I write my posts in RMarkdown if that matters

**Comment by huyb1991** [comment]
@nickeatingpizza I believed this related `shortcode` feature on Hugo and syntax highlight https://gohugo.io/content-management/syntax-highlighting/

Maybe syntax highlight not supporting your code language yet

**Comment by papayarules** [comment]
I use R but I also tried with more common languages but Chroma still doesn't work.
I gave up and installed highlight.js. In 5 minutes everything was up and running fine :)

**Comment by huyb1991** [comment]
@nickeatingpizza This related syntax support by default on Hugo, can we close this issue?

**Comment by papayarules** [comment]
I guess so, I would rather have Chroma working but anyway 🤷‍♂️
